import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <ul className="text-white font-semibold flex flex-col items-center m-4">
            <li><Link href="/landpage">Ir para Land Page</Link></li>
            <li><Link href="/login">Ir para Login</Link></li>
          </ul>
        </main>
        <div className=" flex flex-col items-center justify-center min-h-screen py-2">
          {children}
        </div>
      </body>
    </html>
  );
}
